### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by ottscho** [FriendsOfShopware/packages#101]
Hi,
ich habe Probleme mit den Shopware Plugins (swagimportexport oder swagpaymentpaypalunified).
composer require store.shopware.com/swagimportexport
oder
composer require store.shopware.com/swagpaymentpaypalunified.

für zu folgendem Fehler:
[InvalidArgumentException] Could not find a matching version of package store.shopware.com/swagpaymentpaypalunified. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

Habe die Option minimum-stability bereits von stable auf dev geändert. Leider ohne Erfolg.
Anbei die composer.json

` "name": "shopware/composer-project",
    "description": "Project template for Shopware projects with composer",
    "type": "project",
    "license": "MIT",
    "minimum-stability": "dev",
    "authors": [
        {
            "name": "Shopware",
            "email": "info@shopware.com"
        }
    ],
    "autoload": {
        "classmap": [
            "app/Application.php",
            "app/AppKernel.php",
            "app/ShopwareVersion.php"
        ]
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.friendsofshopware.com/",
            "options": {
                "http": {
                    "header": [
                        "Token: entfernt"
                    ]
                }
            }
        }
    ],
    "require": {
        "php": "^7.2",
        "composer/installers": "^1.0",
        "composer/package-versions-deprecated": "^1.8",
        "shopware/shopware": "^5.6",
        "vlucas/phpdotenv": "^3.1"
    },
    "extra": {
        "installer-paths": {
            "Plugins/Community/Backend/{$name}/": ["type:shopware-backend-plugin"],
            "Plugins/Community/Core/{$name}/": ["type:shopware-core-plugin"],
            "Plugins/Community/Frontend/{$name}/": ["type:shopware-frontend-plugin"]
        }
    },
    "include-path": [
        "engine/Library/"
    ],
    "config": {
        "optimize-autoloader": true,
        "process-timeout": 0,
        "sort-packages": true,
        "platform": {
            "php": "7.2.0"
        }
    },
    "scripts": {
        "post-install-cmd": [
           "./app/bin/post-install.sh"
        ],
        "post-update-cmd":[
           "./app/bin/post-update.sh"
        ]
    }`

**Comment by shyim** [comment]
Did you bought that plugin before in the store?

**Comment by ottscho** [comment]
I do not think so. sorry.
