### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by bonokburn** [FriendsOfShopware/packages#103]
Hi!

When I try to add a package via Composer (e.g. composer require store.shopware.com/dvsncarturl) I get an error message:

The "https://packages.friendsofshopware.com/packages.json" file could not be downloaded (HTTP/1.1 500 Internal Server Error)

The direct call of the URL say: "Oops, We didn't expected an failure here."

Best regards
Frank

**Comment by shyim** [comment]
Hey,
The direct call never really works. 

I can't really see an Issue in Sentry.  Is it possible that you share your Token with me at packages@friendsofshopware.com ?

**Comment by shyim** [comment]
The domain inside the token does not exist anymore in the Shopware Account. 

You can see the actual error by calling it by your self. Composer isn't showing the error message

`curl -H "TOKEN" https://packages.friendsofshopware.com/packages.json`

**Comment by bonokburn** [comment]
Hi Shyim,

thank you very much for your support!
Then I know what the problem is!

Mit freundlichen Grüßen | Best regards

Frank Thunecke
