### ISSUE TITLE
Shopware demo shops not listed under shops

### ISSUE THREAD

**Issue by JoshuaBehrens** [FriendsOfShopware/packages#13]
I have a shopware 6 demo shop but that one is not listed in the drop down. Is this intended?

**Comment by shyim** [comment]
It is not intended, but do you really need them? You can't do anything on that instances

**Comment by JoshuaBehrens** [comment]
I can't :O then it is ok for me

**Comment by shyim** [comment]
You don't access to a console or something else to do composer things :)

**Comment by JoshuaBehrens** [comment]
But can I buy plugins for it?
