### ISSUE TITLE
Plugin dependencies

### ISSUE THREAD

**Issue by 0x4** [FriendsOfShopware/packages#153]
if a plugin requires other plugins from the store (e.g. a foundation plugin that some vendors are using) then the validator for plugin:update fails b/c of missing dependencies.

e.g. package moorlsignin is requiring moorl/foundation - when running the update the following error occurs:

`Required plugin/package "moorl/foundation *" is missing or not installed and activated `

but this plugin is installed - but has another name when installed via packages.friendsofshopware.com

store.shopware.com/moorlfoundation

is there a way to add this alias to the requirement check or something like that?

**Comment by shyim** [comment]
It will be already replaced. Seems like an core issue
![image](https://user-images.githubusercontent.com/6224096/108873411-64019b00-75fb-11eb-9026-392d0a30eab7.png)

**Comment by shyim** [comment]
Its a core issue. To fix it temporary remove these lines https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Plugin/Requirement/RequirementsValidator.php#L146-L148

**Comment by 0x4** [comment]
thanks - the temporary fix helps!

**Comment by mitelg** [comment]
Will be fixed with https://issues.shopware.com/issues/NEXT-13861

**Comment by mitelg** [comment]
the fix will be part of the upcoming Shopware 6.3.5.2 :+1:
