### ISSUE TITLE
automatic plugin update after composer update?

### ISSUE THREAD

**Issue by 0x4** [FriendsOfShopware/packages#170]
is it possible to add a logic to run the shopware update of the plugin automatically after the update of a plugin via composer 

something like
bin/console plugin:update XXX
in the post-update block of the plugins composer.json?
(only if the plugin is installed)

in the correct order - afaik composer installs the dependencies correctly if plugin X depends on plugin Y - so the order of the update is: Y and then X.

At the moment we have sometimes issues when plugins are updated and have crossdependencies. composer update updates the code - but then the plugin:update itself has to be done in the right order.

**Comment by tinect** [comment]
Hey @0x4,

```
bin/console plugin:update ${PLUGINNAME}
bin/console theme:compile
bin/console cache:clear
```

the second line is significant, otherwise you don't have a template using the production template after composer update.

You can update ALL plugins with:
```
bin/console plugin:update -c -n ""
```

You can update ALL plugins with specific vendor name:
```
bin/console plugin:update -c -n "Frosh"
```

**Comment by shyim** [comment]
That commands can be executed with the composer event https://getcomposer.org/doc/articles/scripts.md#package-events

**Comment by 0x4** [comment]
Thanks for your replies. 

I will try that. Any idea how to make sure that the updates are updated in the correct order? 

We had some problems with plugins that have dependencies to other plugins if the update is not executed in the correct order.

**Comment by shyim** [comment]
Thats currently not possible in Shopware
