### ISSUE TITLE
Cannot install any purchased plugin

### ISSUE THREAD

**Issue by tpinne** [FriendsOfShopware/packages#180]
Hi,

for any purchased plugin I tried to install I got the following message, even with `minimum-stability (dev)`:

```
Could not find a matching version of package store.shopware.com/xyz. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

Steps I did:

1. Login
2. Select company
3. Select domain
4. Went to https://packages.friendsofshopware.com/account to see only my packages, which correctly listed all purchased plugins from our account
5. Copy & pasted the repository configuration into my composer.json
6. Selected any plugin
7. Copy & pasted the `composer require store.shopware.com/xyz` into console
8. Executed
9. Got the same message for every plugin I tried

I also tried to require the original composer name of those plugins to no avail just to be sure.

If further information is needed I'm happy to provide them.

**Comment by shyim** [comment]
Which composer version are you using?

**Comment by tpinne** [comment]
`Composer version 1.10.6 2020-05-06 10:28:10`

Will try to update to latest 1.x and try again. Or is version 2 required?

**Comment by tpinne** [comment]
`Composer version 1.10.20 2021-01-27 15:41:06` not working either

**Comment by tpinne** [comment]
`Composer version 2.0.11 2021-02-24 14:57:23` is working.

If the incompatibility with composer version 1 is intended, then I suggest to add some information to the instructions.

**Comment by shyim** [comment]
Should also work with Composer 1. I will later today. currently at work

**Comment by shyim** [comment]
I couldn't reproduce it with the newest v1 composer. Is it maybe possible that you mail me the used token?

**Comment by mrnpnv** [comment]
I can reproduce this issue but only if the Shopware token hasn’t been added to the composer.json. Tested with Composer version 1.10.21 and 2.0.12.

Though after adding the token I still get different error messages:

When using `composer require store.shopware.com/xyz`:

```
  [Seld\JsonLint\ParsingException]
  "https://packages.friendsofshopware.com/login" does not contain valid JSON
  Parse error on line 1:
  <!DOCTYPE html><htm
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```

When using `composer install`: 
```
Failed to extract store.shopware.com/xyz: (9) unzip -qq  '/.../vendor/composer/tmp-991778c2bcfb95e0b8a6405ee087e7f0' -d '/.../vendor/composer/6a0ed6c1'

[/.../vendor/composer/tmp-991778c2bcfb95e0b8a6405ee087e7f0]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /.../vendor/composer/tmp-991778c2bcfb95e0b8a6405ee087e7f0 or
        /.../vendor/composer/tmp-991778c2bcfb95e0b8a6405ee087e7f0.zip, and cannot find /.../vendor/composer/tmp-991778c2bcfb95e0b8a6405ee087e7f0.ZIP, period.

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
Unzip with unzip command failed, falling back to ZipArchive class
Install of store.shopware.com/xyz failed
```

**Comment by shyim** [comment]
@mrnpnv When i install without token I get Warning from packages.friendsofshopware.com: Invalid access token.

The messages only working on newer Composer versions

**Comment by shyim** [comment]
Seems related to prestissimo. Disable it or update to Composer 2
