### ISSUE TITLE
Secret token for private repositories should be moved to auth.json

### ISSUE THREAD

**Issue by ts-mothership** [FriendsOfShopware/packages#192]
### Issue

In the user account there is a button "Setup Repository in Project" to download private repositories. The instruction says it I should add this code snippet into the composer.json:
```
"repositories": [
    {
        "type": "composer",
        "url": "https://packages.friendsofshopware.com/",
        "options": {
            "http": {
                "header": [
                    "Token: obscured"
                ]
            }
        }
    }
]
```

But when adding this into a project which uses a VCS, the token will be committed too. 
This is a security issue.

### Expected behaviour

FriendsOfShopware **should not** use the "Token" header. Instead, the token should be outsourced into the auth.json, like Composer recommended: https://getcomposer.org/doc/articles/authentication-for-private-packages.md

Then the new authentication method should be used instead in documentation and future use.

### More details

I spend a few hours figuring out _if_ and _how_ the token could be placed into the auth.json so that it will be used correctly when installing the plugins. Sadly at the moment it doesn't seem to be possible with the Token header.

Based on https://github.com/composer/composer/blob/2.0.12/src/Composer/Config.php#L138 it seems the settings in auth.json are only merged to the repository sections, if the key is one of these: 'bitbucket-oauth', 'github-oauth', 'gitlab-oauth', 'gitlab-token', 'http-basic', 'bearer'.
I suggest using the Authorization "bearer" method would make most sense here. With that the auth.json could look like this:
```
{
    "bearer": {
        "packages.friendsofshopware.com": "<token>"
    }
}
```
Eventually composer adds the bearer header here: https://github.com/composer/composer/blob/2.0.12/src/Composer/Util/AuthHelper.php#L199

**Comment by shyim** [comment]
Is implemented with an fallback.
Users using the current config will get an warning to switch their configuration.

```
dev@f2d6140fa237 /var/www/html/bla $ composer2 install --ignore-platform-reqs
The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Warning: Accessing packages.shy.ovh over http which is an insecure protocol.
Warning from http://packages.friendsofshopware.com: Usage of Token header is deprecated. Please switch to bearer auth. You can generate a new configuration in the Packages account.
Updating dependencies
Lock file operations: 144 installs, 0 updates, 0 removals
```

I will test it now with all combinations and release it tonight :)

**Comment by ts-mothership** [comment]
Wow that was fast. :) Thank you very much, I'm looking forward to test it.

**Comment by shyim** [comment]
Is deployed
