### ISSUE TITLE
Read dependencies

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/packages#21]
Plugins often bundles libraries or SDKs in their composer.json. Those dependencies should be taken into account when installing the plugin.

**Comment by shyim** [comment]
I have then to manipulate the zip file and this does not feel so good

**Comment by hhoechtl** [comment]
Well, but I think this is necessary to have real dependency management with composer in place.

You would need to delete the `vendor` folder of any plugin from the store if present, so that composer can take over and do its job properly.

We already had such issues very often because many plugins carry a `vendor` folder with a conflicting Guzzle or Monolog version in it.

**Comment by shyim** [comment]
It's not enough to just delete the vendor folder, you have also to check the include of the autoload.php
There are so many edge cases, I can't be done automatically
I know that all problems. The most problematic issue for me is to manipulate the zip file. The plugin is not really reproduce able then anymore, cause the zip files are not equal.

**Comment by hhoechtl** [comment]
Maybe Shopware could extend the plugin management to have 2 versions of the plugin uploaded by the plugin maintainers:
* Including dependencies (as it's know)
* Composer version (without dependencies)

**Comment by shyim** [comment]
As in the latest Shopware version you have to remove dependencies packaged in the vendor folder in the `composer.json`. That makes this topic very complicated.
So I don't want to change here something, cause @mitelg is working on https://github.com/shopwareBoostDay/platform/issues/111 which solves the general issue 😊
