### ISSUE TITLE
SW6 Enterprise plugins are missing

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/packages#28]
![image](https://user-images.githubusercontent.com/5076356/73169771-187d7480-40fd-11ea-8490-b8a43de6922b.png)

![image](https://user-images.githubusercontent.com/5076356/73169781-1e735580-40fd-11ea-856f-ce378b3bab98.png)

**Comment by shyim** [comment]
I checked the internal system. The enterprise plugins are inactive. I contacted the store department for a solution.

**Comment by shyim** [comment]
https://packages.friendsofshopware.com/packages/store.shopware.com/swagb2bplatform/
https://packages.friendsofshopware.com/packages/store.shopware.com/swagenterprisesearchplatform/
