### ISSUE TITLE
Incorrect package version returned for wildcard shops

### ISSUE THREAD

**Issue by icedream** [FriendsOfShopware/packages#312]
## Actual behaviour

For wildcard shops, the repository replicates the Shopware API behavior of limiting available package versions to the *latest* one wrongly and instead the *last released* version will be served:

- If a package has received an update has a *lower* version number than the previous one (example: the previous package version is released as 2.0.1 and the current package version is a backport released as 1.9.2), then the repository will actually serve the older version instead of the newer one.
- If this latest package version is incompatible with the used Shopware version, that package will still be served by the repository, resulting in Composer complaining.

## Expected behaviour

As stated by @shyim in https://github.com/FriendsOfShopware/packages/issues/74#issuecomment-693429550, the repository is supposed to exactly replicate the behavior of the Shopware API: Instead of the *last released* version of a package, the *latest compatible* version of a package is supposed to be served.

## Environment

- Shopware packages version: 0.3.8 (self-hosted copy)
- PHP version: 7.4
- Shopware version: 6.3.5.4/6.4.0.0
- Webserver: Apache 2
- Composer version: 2.0.14/2.1.0
- [The part of the code that is supposed to limit the versions available to install for wildcard shops](https://github.com/FriendsOfShopware/packages/blob/0.3.8/src/Components/PackagistLoader.php#L157-L160)

## Steps to reproduce

I'm specifically going to use [`LoyxxSW6ConversionCheckout`](https://packages.friendsofshopware.com/packages/store.shopware.com/loyxxsw6conversioncheckout/) as an example since it recently released with patches for Shopware 6.3 released as [1.9.21](https://packages.friendsofshopware.com/packages/store.shopware.com/loyxxsw6conversioncheckout/?version=1.9.21) and patches for Shopware 6.4 released as [2.0.1](https://packages.friendsofshopware.com/packages/store.shopware.com/loyxxsw6conversioncheckout/?version=2.0.1).

1. Log in to the repository with a *wildcard shop domain* that has access to `LoyxxSW6ConversionCheckout`.
2. Store its `auth.json` credentials in a Shopware 6.4.0.0 copy.
3. `composer require store.shopware.com/loyxxsw6conversioncheckout` - you will observe here that Composer complains about not finding a compatible version to install, in the cached `packages.json` only the version 1.9.21 will be listed. The expected behavior here is for 2.0.1 to be served.
4. Log in to the repository with a *customer domain* that also has access to this package.
5. Store its `auth.json` credentials in the same Shopware copy and `composer clearcache`.
6. `composer require store.shopware.com/loyxxsw6conversioncheckout` - since the repository will now serve all versions to Composer as can be observed in the cached `packages.json`, it will be able to correctly resolve to 2.0.1 and will install that package.

Reading the code, this problem also affects the ability to install a Shopware 6.3.5.4 compatible version for a plugin that already received a Shopware 6 update - so replace the Shopware version with 6.3.5.4 and try to install such a plugin, and Composer will once again complain about not being able to find a compatible versionuntil you give it non-wildcard access.

**Comment by shyim** [comment]
I don't see a point to fix that as the API delivers only the latest compatible version and this changes on new plugin updates or shop version changing

**Comment by icedream** [comment]
> 
> 
> I don't see a point to fix that as the API delivers only the latest compatible version and this changes on new plugin updates or shop version changing

The problem is the repository does *not* do that currently, and as such does not do what the Shopware API is doing. Instead of returning the latest compatible version (which would be 2.0.1 in the case of LoyxxSW6ConversionCheckout) it returns the last version the manufacturer published (that's 1.9.21 since it was published *after* 2.0.1).

**Comment by shyim** [comment]
I guess I have found an okay way to find the correct latest version. I will test it later and deploy it if its working https://github.com/FriendsOfShopware/packages/commit/30fe9551f7bcecb136893b8fb6cfd3a1f4c5cb18

**Comment by AndreasA** [comment]
This is an important issue as I e.g. also get outdated versions for swagcmsextensions, it says max available version 1.7.2 but I want to install `^1.8` which isn't available. and the b2bplatform only provides 4.3.2 instead of the newest version.

so I hope the fix works.

**Comment by shyim** [comment]
Fix is now live

**Comment by AndreasA** [comment]
I will probably try it on Monday and let you know, if it works now. Thanks for your work.

**Comment by AndreasA** [comment]
@shyim I still get the following errors:

```
- Root composer.json requires store.shopware.com/swagcmsextensions ~1.8, found store.shopware.com/swagcmsextensions[1.0.0, ..., 1.7.2] but it does not match the constraint.
 - Root composer.json requires store.shopware.com/swagcustomizedproducts ~2.10, found store.shopware.com/swagcustomizedproducts[0.9.0, 1.0.0, ..., 1.3.3, 2.0.0, ..., 2.7.0] but it does not match the constraint.
```
