### ISSUE TITLE
B2B platform - reloads composer requirements fatal error

### ISSUE THREAD

**Issue by AndreasA** [FriendsOfShopware/packages#323]
## Actual behaviour

B2B platform suite includes a vendor folder with an autoload.php which is an issue if those packages are already installed which is the case if I install the b2b platform suite using the repository as composer installs it.

## Expected behaviour

To avoid any issues the autoload.php should be an empty php file with maybe `<?php` at the beginning and everything should work fine. Might actually be a general issue with the B2B suite (4.3.2 - don't get a newer version from the repo).

**Comment by shyim** [comment]
That problem isn't from packages. There are already issues in the Issue Tracker for that plugin

**Comment by AndreasA** [comment]
@shyim Ah thanks. great.

**Comment by shyim** [comment]
Enterprise has also an own slack channel. Maybe relevant for you https://shopwarecommunity.slack.com/archives/C0182GQRN2F
