### ISSUE TITLE
Still getting incorrect available packages

### ISSUE THREAD

**Issue by AndreasA** [FriendsOfShopware/packages#326]
## Actual behaviour

Shopware version: 6.3.5.4

Adding 

```json

        "store.shopware.com/swagcmsextensions": "~1.8",
        "store.shopware.com/swagcustomizedproducts": "~2.10",
```

to the composer.json and executing a composer update fails with:

```
  Problem 1
    - Root composer.json requires store.shopware.com/swagcmsextensions ~1.8, found store.shopware.com/swagcmsextensions[1.0.0, ..., 1.7.2] but it does not match the constraint.
  Problem 2
    - Root composer.json requires store.shopware.com/swagcustomizedproducts ~2.10, found store.shopware.com/swagcustomizedproducts[0.9.0, 1.0.0, ..., 1.3.3, 2.0.0, ..., 2.7.0] but it does not match the constraint.
```

However, there is a corresponding version: https://packages.friendsofshopware.com/packages/store.shopware.com/swagcmsextensions/?version=1.8.3 
that also matches the shopware constraint. 

The same for the custoimized products.

## Expected behaviour

Find all available versions.

## Environment

Shopware: 6.3.5.4
Composer: 2.1.3
PHP: 7.4

## Steps to reproduce

See behaviour.

I originally thought this might be solved with https://github.com/FriendsOfShopware/packages/issues/312 but it wasn't. Might not actually be related.

**Comment by shyim** [comment]
Which shopware version is chosen in Wildcard Environment?

**Comment by AndreasA** [comment]
In the account 6.3.5.4 is selected and in the composer.json the following are requested:

```
 "shopware/administration": "~v6.3.0",
        "shopware/core": "~v6.3.0",
        "shopware/elasticsearch": "~v6.3.0",
        "shopware/recovery": "~v6.3.0",
        "shopware/storefront": "~v6.3.0",
```

**Comment by shyim** [comment]
Hmm I will look tonight thats my free time project :)

**Comment by AndreasA** [comment]
@shyim 

It isn't that high a priority for now as the project currently has setup the dependencies differently but for future updates, it would be nice to switch to the repository.

So whenever you find the time.

**Comment by AndreasA** [comment]
Just wondering but shouldn't the repository just deliver all available packages and let composer (client) decide which can be installed because the conflicts above look like various versions (not just the latest) are missing.

But I admit I never setup a composer repository, so I am not 100% sure, if that would work :smile:

**Comment by icedream** [comment]
> Just wondering but shouldn't the repository just deliver all available packages and let composer (client) decide which can be installed because the conflicts above look like various versions (not just the latest) are missing.

This is indeed the technically correct approach for Composer to be able to properly resolve dependencies on a version-level. However the explanation for why this was done this way was given in the indeed related issue https://github.com/FriendsOfShopware/packages/issues/312, the restrictions for which versions are exposed to Composer are inspired from how Shopware's official backend differently exposes plugin versions for wildcard domains (which will only give you the latest version) and partner shop domains (which will give you all previous versions as well).

I hope that issue will be tackled once Shopware starts providing an official Composer repository, this can't be single-handedly solved by @shyim for above reason, even though it could technically be done.

**Comment by AndreasA** [comment]
Why would wildcard domains be handled different to partner shop domains? also if I have multiple hosts with the wildcard domain it doesn't mean all hosts work with same Shopware version and plugin versions as the code base might be different. Not to mention only the latest means I would always need to update to the latest Shopware version for all hosts.

Sounds kind of weird but yes it probably makes it more complicated and personally I would be really happy with an official repository by Shopware instead of just one person in their free time. After all there just is never enough time for one person in their free time and they want to do other stuff as well in their free time like having free time :smile:

**Comment by shyim** [comment]
Hey,

We are planning to release the official solution in the next week. So it doesn't make sense to invest any more time here :). The wildcard are implemented in same way as normal shops and doesn't differ anymore

**Comment by AndreasA** [comment]
Hi @shyim can you let me know once the official solution is live, so I can try it again?

**Comment by AndreasA** [comment]
Hi @shyim I tried the official Shopware packages today and it works great and provides the correct versions.

Thanks to all involved in making an official Shopware packages repository a reality and of course to you for providing the friends of shopware version beforehand but having it official is just better, e.g. easier to maintain than just by one person.
