### ISSUE TITLE
Missing plugin releases

### ISSUE THREAD

**Issue by tehplague** [FriendsOfShopware/packages#38]
The following plugin releases are missing:

- NetiStoreLocator 6.5.1 (https://store.shopware.com/neti00423/filial-haendlersuche-storelocator.html)
- NetiStoreBusinessHours 5.1.3 (https://store.shopware.com/neti01074/oeffnungszeiten-fuer-filialen-storebusinesshours.html)
- NetiStorePickUp 5.0.6 (https://store.shopware.com/neti00659/click-collect-selbstabholung-in-der-filiale-storepickup.html)
- NetiStoreSelect 3.2.1 (https://store.shopware.com/neti760995719106/storeauswahl-per-karten-layer-storeselect.html)
- SwagBackendOrder 2.6.2 (https://store.shopware.com/swag860272615705f/backend-bestellungen.html)
- SwagImportExport 2.10.6 (https://store.shopware.com/swagef36a3f0ee25f/shopware-import/export.html)

Most of them are older than 14 days, so this might be a larger issue and there might be more missing package releases.

**Comment by shyim** [comment]
Whoops. A Plugin Producer got a rename of his prefix. This broke the entire import. 🙈.
It's currently indexing. Thats for the report

**Comment by shyim** [comment]
It's updated.
