### ISSUE TITLE
Could not open input file: sw:thumbnail:generate

### ISSUE THREAD

**Issue by d-a-u** [FriendsOfShopware/packages#386]
### Question

Hello,

I have installed your plugin, but I have little problems

Shopware 5.7.2

# whereis cwebp
cwebp: /usr/bin/cwebp

![grafik](https://user-images.githubusercontent.com/87116906/124884581-b358ce80-dfd2-11eb-9429-ca599a2cad8b.png)

But if I will generate the pictures, I became following error:
/usr/bin/php sw:thumbnail:generate -f
Could not open input file: sw:thumbnail:generate

If I will download the package:
/usr/bin/php frosh:webp:download-google-binaries
Could not open input file: frosh:webp:download-google-binaries

Can you tell me, what is wrong on my server?

Many Thanks from
d-a-u

**Comment by shyim** [comment]
It should be
/usr/bin/php bin/console sw:thumbnail:generate -f


Thats also the wrong repository
