### ISSUE TITLE
Missing plugin releases

### ISSUE THREAD

**Issue by kris-terziev** [FriendsOfShopware/packages#40]
Problem 1
    - The requested package store.shopware.com/memopostcodeplugin could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package store.shopware.com/wbmtagmanagerecomm could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package store.shopware.com/netzpblog6 1.0.5 exists as store.shopware.com/netzpblog6[1.0.6] but these are rejected by your constraint.
  Problem 4
    - The requested package store.shopware.com/brandcrockarticlestocklevel could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package store.shopware.com/rhwebfurnitureone 1.3.1 exists as store.shopware.com/rhwebfurnitureone[1.3.2] but these are rejected by your constraint.

**Comment by shyim** [comment]
Did you bought the plugins before in the store?

**Comment by kris-terziev** [comment]
Hey shyim,

Indeed that was the problem. I made a mistake with the wildcard domain I was supposed to use.
