### ISSUE TITLE
Enhance statistics

### ISSUE THREAD

**Issue by ededagic** [FriendsOfShopware/packages#42]
It would be nice to separate Shopware 5 and 6 packages statistics and give the full list of package downloads. It could be a nice indicator for digital agencies to follow the actual trends and make recommendations. I could imagine a separate site with filters like System and time period. that would be enough for the beginnen. a list is actually enough, with the number of downloads like here: https://packages.friendsofshopware.com/browse

**Comment by shyim** [comment]
I guess its better to have this in the store. We can't show an overall of all downloads. I will forward it to plugin managment
