### ISSUE TITLE
Rewrite dependencies of Shopware 6 plugins to local packages

### ISSUE THREAD

**Issue by c-gross** [FriendsOfShopware/packages#43]
One dependency of
https://packages.friendsofshopware.com/packages/store.shopware.com/moorlcmsctabanner/
is not available

https://packagist.org/search/?q=moorl%2Ffoundation&reason=package_not_found

Problem 1
    - store.shopware.com/moorlcmsctabanner 1.0.4 requires moorl/foundation * -> no matching package found.
    - store.shopware.com/moorlcmsctabanner 1.0.2 requires moorl/foundation * -> no matching package found.
    - store.shopware.com/moorlcmsctabanner 1.0.1 requires moorl/foundation * -> no matching package found.
    - store.shopware.com/moorlcmsctabanner 1.0.0 requires moorl/foundation 0.0.1 -> no matching package found.
    - Installation request for store.shopware.com/moorlcmsctabanner ^1.0 -> satisfiable by store.shopware.com/moorlcmsctabanner[1.0.0, 1.0.1, 1.0.2, 1.0.4].

**Comment by shyim** [comment]
Did you bought both plugins in the store?

**Comment by c-gross** [comment]
Nope. It's was not mentioned in the plugin description in the store and not on friendsofshopware plugin description as well that you have to order a 2nd plugin to be able to install it. Just checked all Moorl Plugins and found it.

But it's still not working. I installed store.shopware.com/moorlfoundation now but store.shopware.com/moorlcmsctabanner is still throwing the same composer error.

**Comment by c-gross** [comment]
Same for another plugin using some extra dependency. And there is only one SW6 plugin from this company.

composer require store.shopware.com/hbdevlegaltext                                                                                                                                                                                                                                ✔  1303  12:00:56
Using version ^2.0 for store.shopware.com/hbdevlegaltext
./composer.json has been updated
> [ ! -f vendor/autoload.php ] || bin/console system:update:prepare
Run Update preparations
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - store.shopware.com/hbdevlegaltext 2.0.1 requires haendlerbund/legal-text-api-connector ^1.0.0 -> no matching package found.
    - store.shopware.com/hbdevlegaltext 2.0.0 requires haendlerbund/legal-text-api-connector ^1.0.0 -> no matching package found.
    - Installation request for store.shopware.com/hbdevlegaltext ^2.0 -> satisfiable by store.shopware.com/hbdevlegaltext[2.0.0, 2.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by shyim** [comment]
Cause the store does not have any restriction on composer name. Everyone can use anything as composer name. This makes dependencies very hard.
So I guess we need here a dirty fix to rewrite the given dependencies of the plugins any link to the packages one.

That will be much work 😭

**Comment by c-gross** [comment]
So that will take some time. Is there some workaround or is a manual installation the only solution in the meantime?

**Comment by shyim** [comment]
You could do in the meanwhile replace that missing dependencies. Then it should install. 
https://getcomposer.org/doc/04-schema.md#replace

**Comment by shyim** [comment]
Fixed see https://packages.friendsofshopware.com/packages/store.shopware.com/moorlcmsctabanner/

**Comment by c-gross** [comment]
Nice just tested and the first plugin ist working. 

The second plugin has still the error:
https://packages.friendsofshopware.com/packages/store.shopware.com/hbdevlegaltext/
Is still using a different name.

**Comment by shyim** [comment]
It's not an issue from packages anymore. Please contact the plugin manufacturer

```json
"require": {
        "shopware/core": "^6.1.5",
        "haendlerbund/legal-text-api-connector": "^1.0.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://gitlab-proxy.haendlerbund.de/composer-packages/legal-text-api-connector"
        }
    ],
```

**Comment by c-gross** [comment]
Just found another issue...
The composer.json of the plugin itself will still use the "old" package name. I deleted vendor and composer.lock to make sure it's not using old files.

The plugin composer.json of moorlcmsctabanner is still looking for moorl/foundation and will fail when I try to install it since it does not exist under this name in vendor. When I change the plugin composer.json to store.shopware.com it is working but that doesn't work for deployments. 

`"require": {
        "shopware/core": "*",
        "moorl/foundation": "*"
    },`

**Comment by windaishi** [comment]
Why do you override the vendor-prefix of the plugin packages names with "store.shopware.com" at all? Isn't that totally unexpected and unnecessary?

**Comment by shyim** [comment]
Cause they are no rules currently. everyone can use what they want. And the big main reason the composer name is not saved in the store. They still use the old plugin name as unique. So I do the same there. I will later add a provide to the packages, who as an another name too. That should fix that

**Comment by shyim** [comment]
Is now fixed with https://github.com/FriendsOfShopware/packages/commit/7cd2ef0aa0cd8c23c90883b734d41d133a675e08
and can be even installed in admin 😅
