### ISSUE TITLE
DevertPDFExport : Can´t find the pdf-file-name adjustment in my backend. THX for help!

### ISSUE THREAD

**Issue by rolf-pluemper** [FriendsOfShopware/packages#453]
### PHP Version

7.4

### Shopware Version

6.3.4.1

### Actual behaviour

Can´t find the pdf-file-name adjustment in my backend. THX for help!

### Expected behaviour

Adjustment of PDF file ... not ... 43445364565432453...

### Steps to Reproduce?

First install

**Comment by mitelg** [comment]
what does this have to do with this repository?

I guess you should contact the plugin manufacturer 🙂

**Comment by shyim** [comment]
As mitelg said please contact the manufacturer using https://account.shopware.com
