### ISSUE TITLE
store.shopware.com/swagpaypal 3.5.0 not available

### ISSUE THREAD

**Issue by amtee** [FriendsOfShopware/packages#458]
### PHP Version

PHP 7.4.19

### Shopware Version

6.4.3.1

### Actual behaviour

$ composer update store.shopware.com/swagpaypal

gives:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires store.shopware.com/swagpaypal ^3.5.0, found store.shopware.com/swagpaypal[0.9.0, ..., 0.13.0, 1.0.0, ..., 1.10.0, 2.0.0, ..., 2.2.6, 3.0.0, ..., 3.4.0] but it does not match the constraint.
```

### Expected behaviour

downloads and installs `store.shopware.com/swagpaypal ^3.5.0`

### Steps to Reproduce?

composer update store.shopware.com/swagpaypal with a ^3.2 or ^3.5 constraint in composer.json

**Comment by amtee** [comment]
The plugin was updated today, so I'ma check back on that tomorrow morning.

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/129964995-bbc32224-4d9a-4ec0-bb2c-e8c6b5c24e88.png)
looks okay for me :D
