### ISSUE TITLE
Plugin missing - Google Tag Manager 

### ISSUE THREAD

**Issue by fbatschi** [FriendsOfShopware/packages#464]
### Question

The Plugin https://store.shopware.com/en/shops29034289413f/google-tag-manager-cloud.html seems to be missing in the package database. 

Who is best to talk to in order to include it?

**Comment by shyim** [comment]
It's not a plugin it's an app.  They are currently not installable using Composer: https://issues.shopware.com/issues/NEXT-15992

**Comment by fbatschi** [comment]
ok thanks. thats unfortunate and not easy to distinguish in the shopware store.
