### ISSUE TITLE
[Composer\Downloader\TransportException]

### ISSUE THREAD

**Issue by wildi1** [FriendsOfShopware/packages#503]
### PHP Version

7.3

### Shopware Version

5.6.10

### Actual behaviour

When running composer update -o -vvv the following exception occurs

[Composer\Downloader\TransportException]                                                               
The "https://packages.friendsofshopware.com/packages.json" file could not be downloaded (HTTP/2 500 )  
                                                                                                         
When opening https://packages.friendsofshopware.com/packages.json also an Error occurs:
Oops.
We didn't expected an failure here.
Please create an Github Issue at packages and fill out the Dialog.

### Expected behaviour

Running composer update / install without errors

### Steps to Reproduce?

Run composer update -o -vvv

**Comment by shyim** [comment]
Is fixed and please see https://shyim.me/blog/deprecation-frosh-packages/
