### ISSUE TITLE
Getting error at Installation via composer 

### ISSUE THREAD

**Issue by marsium** [FriendsOfShopware/packages#571]
### Question

Hello.

composer require store.shopware.com/gbmedtopseller  produces an error:

**[InvalidArgumentException]                                                                                                                                                                                                  
  Could not find a matching version of package store.shopware.com/gbmedtopseller. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability   
  (stable).**  

auth.json has the right token and composer.json has 
shopware-packages": {
            "type": "composer",
            "url": "https://packages.shopware.com"
        },

My shopware version is 6.4.1.2

Could someone please help?
Thank you.

**Comment by shyim** [comment]
Hey,

please use the official support way of Shopware. Community Slack or Contact using Accout
