### ISSUE TITLE
Unable to install  SwagMigrationMagento

### ISSUE THREAD

**Issue by abvdveen** [FriendsOfShopware/packages#70]
When I try to install  SwagMigrationMagento I get the error 'Required plugin/package "swag/migration-assistant ~2.1" does not match installed version 2.1.0.'

Changing the requirement in swagmigrationmagento/composer.json from ~2.1 to ^2 solves the problem, but I have to be overlooking something obvious that causes the problem. What is it? :)

composer require store.shopware.com/swagmigrationmagento
bin/console plugin:install SwagMigrationMagento

**Comment by shyim** [comment]
Hey,

thanks for your Report. I could reproduce it too. The Shopware Requirements Checker while installing does not recognize replaced packages.

I have created a Ticket: https://issues.shopware.com/issues/NEXT-10746 I will discuss it internally and maybe build an workaround here to get it also working :)

**Comment by shyim** [comment]
Fix is now live.

```bash
rm -rf composer.lock vendor
composer clearcache
composer install
```

Should fix it :)
