### ISSUE TITLE
Missing latest version of store.shopware.com/swagpaymentpaypalunified

### ISSUE THREAD

**Issue by Sergiuku** [FriendsOfShopware/packages#72]
Version 3.0.0 can't be installed by composer.

**Comment by shyim** [comment]
Should be now listed. Sorry

**Comment by mitelg** [comment]
wie changed the name in the composer.json, because of the composer2 compatibility 

https://github.com/shopwareLabs/SwagPaymentPayPalUnified/commit/e49f0436f683fef7900e48aa0283ef544e70dd2f

maybe it is enough if you clear the cache?

**Comment by shyim** [comment]
The cronjob didn't run :sweat_smile: to update data

**Comment by Sergiuku** [comment]
Everything is fine now. Thank you. 👍
