### ISSUE TITLE
The server returned a "500 Internal Server Error". when I select the shop

### ISSUE THREAD

**Issue by Sergiuku** [FriendsOfShopware/packages#73]
When I'm trying to select the shop and submit the selected shop this happens:

URL: https://packages.friendsofshopware.com/account

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Do you have any idea why?

**Comment by shyim** [comment]
Can you

**Comment by shyim** [comment]
Wildcard Domains don't have an active subscription https://github.com/FriendsOfShopware/packages/blob/live/src/Components/Api/Client.php#L120

This will later fail here https://github.com/FriendsOfShopware/packages/blob/live/src/Struct/Shop/Shop.php#L67
