### ISSUE TITLE
Cannot install older paypal versions and WilderCard plugins are not visible 

### ISSUE THREAD

**Issue by Sergiuku** [FriendsOfShopware/packages#74]
When I'm trying to install paypal 2.8.0 via composer this error is displayed.
 - The requested package store.shopware.com/swagpaymentpaypalunified 2.8.0 exists as store.shopware.com/swagpaymentpaypalunified[3.0.0] but these are rejected by your constraint.

The second issues:
I have some plugins in the Wildcard environments, the shop is visible on https://packages.friendsofshopware.com/ , 
but the plugins are not.

**Comment by shyim** [comment]
You cannot install older versions in Wildcard Domains. It's a Shopware API limitation
