### ISSUE TITLE
latest.sql empty

### ISSUE THREAD

**Issue by acydburn** [FriendsOfShopware/packages#75]
Hi,

we wanted to create a mirror for internal usage (if there is a need for an external mirror we would be glad to help, just contact me) but the latest.sql is empty. :)

https://packages-dump.friendsofshopware.com/
https://packages-dump.friendsofshopware.com/files/latest.sql

Does this happen from time to time (no problem then) or is it currently broken/not working.

Best,
Meik

**Comment by shyim** [comment]
Hey,

Just using now a Tool to dump it instead a bash. Should work now better
