### ISSUE TITLE
Packages info not uptodate?

### ISSUE THREAD

**Issue by mmodler** [FriendsOfShopware/packages#76]
Just did a composer update & deploy and after that the admin notified me of plugin updates. Seems like the hourly package info update is not working atm?

https://packages-dump.friendsofshopware.com

**Comment by acydburn** [comment]
They fixed it recently, but the latest.sql is still empty. We use the latest.packages.sql.gz file. If you use https://packages.friendsofshopware.com/ directly the dump is not relevant. :)

**Comment by shyim** [comment]
Should work now much more stable. Thanks!
