### ISSUE TITLE
Unable to install FriendsOfShopware Development Helper

### ISSUE THREAD

**Issue by abvdveen** [FriendsOfShopware/packages#81]
Using  composer require store.shopware.com/froshdevelopmenthelper on a 6.3.1.1 Shopware instance gives

 [InvalidArgumentException] Could not find a matching version of package store.shopware.com/froshdevelopment-helper. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by shyim** [comment]
I couldn't find any issues.  I guess you didn't bought the Plugin for the domain?
You need to buy also free plugins: https://store.shopware.com/en/frosh14352927691f/development-helper-dev-tools.html

**Comment by abvdveen** [comment]
Sorry, my mistake - didn't know you had to order free plugins. However, I now have ordered the plugin for the domain, got a confirmation for that and still get the same composer message. Am I missing something else?

**Comment by shyim** [comment]
Did cleared redis cache. Should be now listed. Will be better with next release

**Comment by abvdveen** [comment]
Still the same error I'm afraid.

**Comment by abvdveen** [comment]
Same problem with this plugin I bought: composer require store.shopware.com/cogidetectlocation

**Comment by abvdveen** [comment]
Sorry, my mistake (again): just noticed in my account that the plugin is not (yet) compatible with Shopware 6.3.1.1 - will try again when they have adjusted their version to be compatible.
