### ISSUE TITLE
HTTP 500 if Shopware account is inactive (minor glitch)

### ISSUE THREAD

**Issue by tehplague** [FriendsOfShopware/packages#82]
I just converted my old Shopware ID into an e-mail based account. However, before completing the confirmation process I tried to login into the package repository which ended up in an HTTP error 500.

Usually this should not happen in the wild but I suggest checking if this constellation can be caught at login time.

**Comment by shyim** [comment]
The only last error tracked is that the shopware login is failed.

Can you execute this in your shell?

```
curl -X POST -d '{"shopwareId": "MY_EMAIL", "password": "MY_PASSWORD"}' https://api.shopware.com/accesstokens
```

**Comment by tehplague** [comment]
API answers with
`{"success":false,"code":"UsersException-16"}`

**Comment by shyim** [comment]
```
public const EMAIL_ADDRESS_UNVERIFIED = 16;
```

You need to verify your email address :)

**Comment by tehplague** [comment]
I know about this :)
But I still don't think that the application should answer with HTTP 500.
