### ISSUE TITLE
Setup instruction not working

### ISSUE THREAD

**Issue by tibuprophen** [FriendsOfShopware/packages#97]
# Problem
When I try to set-up this repository for my own with docker-compose, it does not work properly. I followed the instructions on the README.md on tag 0.1.15, but I end up getting error-responses when I search for packages. I imported the dump from https://packages-dump.friendsofshopware.com/. 
This is the response of the search request:
![image](https://user-images.githubusercontent.com/952777/99538108-c7e94780-29ac-11eb-9565-533ba9b842eb.png)

I think I'm doing something wrong setting up the repository, but I just followed the simple instructions. Thanks for any help!

**Comment by shyim** [comment]
```
./bin/console search:package:index
```

**Comment by tibuprophen** [comment]
Thanks that worked!
